### ISSUE TITLE
Lungmap `dev` snapshot is in wrong location

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/dcp2#47]
All snapshots from the `dev` refresh are in the `us-central1` BQ location. When incorporating those snapshots into Azul, we had to remove the Lungmap snapshot (`lungmap_dev_20210412__20210414`) because it is in the `US` location. All snapshots indexed by one Azul instance must be in the same location so that they can be covered by a single BQ slot commitment.

We can either create a new Azul instance specifically for `Lungmap` or copy the snapshot to `us-central1`. The former would cause continuing cost for maintaining that instance and for the corresponding cloud infrastructure. The latter would be a one-time operation.

**Comment by hannes-ucsc** [comment]
Name of copy should match new naming convention with project ID in dataset name.

**Comment by theathorn** [comment]
No longer planning to support a lungmap dev catalog.
