### ISSUE TITLE
Copy LungMAP snapshots to TDR `dev`

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/dcp2#62]
Copy 

~- `lungmap_prod_00f056f273ff43ac97ff69ca10e38c89__20220308_20220308`~
- `lungmap_prod_1bdcecde16be420888f478cd2133d11d__20220308_20220308`
- `lungmap_prod_2620497955a349b28d2b53e0bdfcb176__20220308_20220308`
- `lungmap_prod_00f056f273ff43ac97ff69ca10e38c89__20220308_20220314_lm2`
- `lungmap_prod_20037472ea1d4ddb9cd356a11a6f0f76__20220307_20220310_lm2`
- `lungmap_prod_f899709cae2c4bb988f0131142e6c7ec__20220310_20220311_lm2`

from TDR new prod to TDR dev.

**Comment by theathorn** [comment]
Completed as per this [Slack thread](https://humancellatlas.slack.com/archives/C01DQFA5F5Y/p1648580067305419).
